project:
  type: website
  output-dir: docs

website:
  title: "biRd"
  description: "Aventuras em ornitologia, ecologia e estatística"
  navbar:
    left:
      - text: "Início"
        file: index.qmd
      - text: "Sobre"
        file: about.qmd
    right: 
      - icon: github
        href: https://github.com/Ivana-Cardoso
      - icon: twitter
        href: https://twitter.com
        
    logo: biRd.png
    
format:
  html:
    theme: theme.scss
    mainfont: "Open Sans"

editor: visual

