project:
  type: website
  output-dir: docs
  
website:
  title: "biRd blog"
  description: "Aventuras em ornitologia, ecologia e estatística"
  navbar:
    left:
      - text: "Início"
        file: index.qmd
      - text: "Sobre"
        file: about.qmd
    right: 
      - icon: github
        href: https://github.com/Ivana-Cardoso
      - icon: twitter
        href: https://twitter.com/Iv_Cardoso
    logo: round_biRd.png
    comments: 
    giscus: 
      repo: Ivana-Cardoso/Ivana-Cardoso.github.io
      
format:
  html:
    theme:
      - theme.scss
   


editor: visual

