project:
  type: website
  output-dir: docs
  
website:
  site-url: https://ivana-cardoso.github.io/
  title: "biRd blog"
  image: biRd.png
  description: "Aventuras em ornitologia, ecologia e estatística"
  announcement: 
    icon: binoculars-fill
    dismissable: true
    content: "A ciência se torna ainda mais bela quando explorada em conjunto. **Seja bem-vinda(o) ao biRd blog!**"
    type: primary
    position: below-navbar
  navbar:
    left:
      - text: "Postagens"
        file: index.qmd
      - text: "Sobre o blog"
        file: about.qmd
      - text: "Sobre a autora"
        file: about_author.qmd
    right: 
      - icon: github
        href: https://github.com/Ivana-Cardoso
      - icon: rss
        href: index.xml
    logo: round_biRd.png
  page-footer: "Este blog foi construído com [Quarto v.1.5.57](https://quarto.org/) no [R v.4.3.2](https://www.r-project.org/)"

format:
  html:
    theme:
      - theme.scss

editor: visual

