project:
  type: website
  output-dir: docs
  
website:
  site-url: https://ivana-cardoso.github.io/
  title: "biRd blog"
  description: "Aventuras em ornitologia, ecologia e estatística"
  navbar:
    left:
      - text: "Postagens"
        file: index.qmd
      - text: "Sobre o blog"
        file: about.qmd
      - text: "Sobre a autora"
        file: about_author.qmd
    right: 
      - icon: github
        href: https://github.com/Ivana-Cardoso
      - icon: twitter
        href: https://twitter.com/Iv_Cardoso
    logo: round_biRd.png
    
format:
  html:
    theme:
      - theme.scss

editor: visual

