{
  "hash": "e16ad5394162074a85d4615c4815eb3c",
  "result": {
    "markdown": "---\ntitle: \"Como calcular a composição da paisagem no R?\"\nauthor: \"Ivana Cardoso\"\ndate: \"2024-02-26\"\nimage: \"Paisagem_capa.png\"\ncategories: \n  - R\n  - ecologia de paisagem\nexecute:\n  freeze: auto\n---\n\n\n[Em ecologia de paisagens](https://www.scielo.br/j/bn/a/Jbchd6rjY35PGkY5BHPz63S/), uma paisagem pode ser definida como um mosaico de usos do solo que interagem entre si em uma determinada escala, e pode ser caracterizada por sua composição e configuração. A composição da paisagem diz respeito a quantidade dos diferentes elementos na paisagem, enquanto a configuração diz respeito ao arranjo espacial desses elementos. \n\nPor exemplo, a cobertura florestal é uma medida de composição da paisagem que representa a quantidade de floresta, geralmente expressa em porcentagem, dentro da paisagem. [Maior cobertura florestal](https://onlinelibrary.wiley.com/doi/epdf/10.1111/ele.13535) pode indicar maior diversidade de espécies e disponibilidade de recursos. \nJá o número de fragmentos é uma medida de configuração da paisagem que representa o nível de fragmentação dessa paisagem. Para um determinado valor de habitat, [mais fragmentos](https://onlinelibrary.wiley.com/doi/epdf/10.1111/ele.13535) podem facilitar a movimentação das espécies.\n\nA escala em que a composição e a configuração da paisagem são calculadas influencia fortemente a relação das espécies com a paisagem. Por isso, é indicado fazer uma análise multi-escalar para selecionar uma escala, chamada [escala de efeito](https://onlinelibrary.wiley.com/doi/pdf/10.1111/geb.12233), que produza a relação mais forte entre sua variável resposta relacionada às espécies e sua variável preditora relacionada à paisagem. Por exemplo, em um estudo com aves foi utilizada uma análise multi-escalar para avaliar a relação entre [número de espécies e quantidade de habitat disponível](https://onlinelibrary.wiley.com/doi/abs/10.1111/jbi.13499) na paisagem.\n\nNo post de hoje, vamos aprender a calcular a composição da paisagem no software R utilizando o pacote [landscapemetrics](https://r-spatialecology.github.io/landscapemetrics/index.html). Para isso, utilizaremos, para fins didáticos, poucas paisagens e apenas uma escala de 2000 m. No entanto, lembre-se de avaliar se uma análise multi-escalar seria adequada para o seu caso.\n\nA área de estudo que escolhi foi a [Reserva de Desenvolvimento Sustentável (RDS) do Rio Negro](https://ppbio.inpa.gov.br/sitios/RDS_Rio_Negro), no Amazonas. Então, baixei o raster de cobertura e uso do solo da área no [MAPBIOMAS](https://brasil.mapbiomas.org/colecoes-mapbiomas/) para o ano de 2022 (coleção 8). O arquivo está disponível no meu [GitHub](https://github.com/Ivana-Cardoso/Ivana-Cardoso.github.io/tree/main/posts), mas caso prefira baixar diretamente do site original, sugiro utilizar o [Toolkit](https://www.youtube.com/watch?v=OBqaoSuLGbk&ab_channel=MapBiomasBrasil) no Google Engine e prestar atenção ao Sistema de Referência de Coordenadas (CRS) escolhido. \n\n## Calculando a composição da paisagem\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Carregue os pacotes necessarios\nlibrary(raster)\nlibrary(landscapemetrics)\nlibrary(sf)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Importe o raster\nRDS <- raster(\"RDS_Rio_Negro.tif\")\n\n# Veja qual a projecao do raster\nproj4string(RDS)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"+proj=utm +zone=20 +south +datum=WGS84 +units=m +no_defs\"\n```\n:::\n:::\n\nO nosso raster está no datum WGS-84, no formato de saída UTM, zona 20, hemisfério sul. É importante atentar para o formato de saída, pois queremos que as unidades do mapa sejam metros, e não graus. Isso facilita a compreensão do tamanho das nossas paisagens. É mais intuitivo entender que o tamanho das paisagens é de 2000 m do que 0.018 graus, não é?\n</br>\nLembre-se de verificar a [zona UTM](https://forest-gis.com/2016/06/um-pouco-sobre-a-projecao-utm.html/) da sua ára de estudo e garantir que seu raster esteja na projeção correta.\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cheque o raster\ncheck_landscape(RDS) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  layer       crs units   class n_classes OK\n1     1 projected     m integer         9  ✔\n```\n:::\n:::\n\nObserve que nossas unidades estão em metros (coluna 'units'), nosso raster possui nove classes (coluna 'n_classes') de uso e cobertura do solo, e que o valor dessas classes é especificado por números inteiros (coluna 'class').\n</br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Crie as coordenadas centrais das paisagens\ncoordenadas <- data.frame(X = c(774310, 757581, 745481),\n                          Y = c(9658335, 9670747, 9688402))\n\n# Identifique as paisagens\ncoordenadas$id <- c(1, 2, 3)\n\n# Transforme a tabela de coordenadas em pontos espaciais\npontos <- st_as_sf(coordenadas, \n                        coords = c(\"X\", \"Y\"), crs = crs(RDS)) \n```\n:::\n\n\nSe você quiser visualizar seus dados **diretamente** no R antes de iniciar as análises, você pode utilizar os comandos abaixo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Crie as paisagens de 2000 m\npaisagens <- st_buffer(pontos, dist = 2000)\n\n# Visualize os dados\nplot(RDS, col=gray.colors(34))\npoints(coordenadas, pch = 16)\nplot(paisagens, add = TRUE, color=\"black\") \n```\n:::\n\n\n![ ](RDS.png){width=\"60%\"}\n\nEu criei esse mapa no QGIS V.3.34.3, mas ele é essencialmente o mesmo do mapa gerado a partir dos comandos acima, com exceção das cores. Eu escolhi fazer no QGIS apenas para mudar as cores sem incluir e dificultar o código com ações que não são o objetivo desse tutorial.\nOs pontos das nossas coordenadas estão representadas no mapa pela bolinha preta com contorno branco e as paisagens de 2000 m estão representadas pelo círculo tracejado.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calcule a composição da paisagem\ncomposicao <- landscapemetrics::sample_lsm(RDS, y = pontos, size = 2000,\n                                           shape = \"circle\", plot_id = pontos$id,\n                                           what = \"lsm_c_pland\")\n```\n:::\n\nPara amostrar paisagens em uma determinada escala ao redor de pontos de interesse utilizamos a função [sample_lsm](https://r-spatialecology.github.io/landscapemetrics/reference/sample_lsm.html). Dentro dessa função especificamos nosso raster (RDS), os pontos centrais de interesse (y = pontos), a escala da nossa paisagem (size = 2000), o formato da nossa paisagem (shape = \"circle\"), o identificador de cada paisagem (plot_id = pontos$id) e o que gostaríamos de calcular dentro dessa paisagem (\"lsm_c_pland\").\nA função [lsm_c_pland](https://r-spatialecology.github.io/landscapemetrics/reference/lsm_c_pland.html?q=lsm_c_pland#ref-usage) calcula a porcentagem de cada classe do raster dentro da paisagem. No nosso caso, essa função calculou a porcentagem de cada uso do solo nas paisagens.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualize os resultados\ncomposicao\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 16 × 8\n   layer level class    id metric   value plot_id percentage_inside\n   <int> <chr> <int> <int> <chr>    <dbl>   <dbl>             <dbl>\n 1     1 class     3    NA pland  74.4          1              102.\n 2     1 class     6    NA pland   6.75         1              102.\n 3     1 class    11    NA pland   1.23         1              102.\n 4     1 class    12    NA pland   0.0352       1              102.\n 5     1 class    15    NA pland   0.458        1              102.\n 6     1 class    33    NA pland  17.2          1              102.\n 7     1 class     3    NA pland  97.8          2              102.\n 8     1 class     6    NA pland   1.06         2              102.\n 9     1 class    15    NA pland   0.810        2              102.\n10     1 class    33    NA pland   0.374        2              102.\n11     1 class     3    NA pland  68.1          3              102.\n12     1 class     6    NA pland   2.26         3              102.\n13     1 class    11    NA pland   2.18         3              102.\n14     1 class    12    NA pland   0.507        3              102.\n15     1 class    15    NA pland   9.73         3              102.\n16     1 class    33    NA pland  17.2          3              102.\n```\n:::\n:::\n\n\nEssa tabela mostra nossos resultados. Preste atenção na coluna três, chamada \"class\", na coluna seis, chamada \"value\", e na coluna sete chamada \"plot_id\".\n\nA coluna três indica os valores dos pixels que representam as classes. Já que utilizamos o raster do MAPBIOMAS, temos que consultar o [código de legenda](https://brasil.mapbiomas.org/wp-content/uploads/sites/4/2023/08/Legenda-Colecao-8-LEGEND-CODE.pdf) para entender o que é cada classe do raster. \n\nA coluna seis indica o valor, em porcentagem, de cada classe na paisagem.\n\nA coluna sete indica a qual paisagem pertencem os valores. Com nossos resultados podemos concluir que:\n\nA composição da **paisagem 1** é: \n</ul>\n  - 74.4% de Formação Florestal (classe 3), \n  - 6.75% de Floresta Alagável (classe 6), \n  - 1.23% Campo Alagado e Área Pantanosa (classe 11), \n  - 0.0352% de Formação Campestre (classe 12), \n  - 0.458% de Pastagem (classe 15),\n  - 17.2% de Rio (classe 33).\n</ul>\n  \nA composição da **paisagem 2** é:\n</ul>\n  - 97.8% de Formação Florestal (classe 3),\n  - 1.06% de Floresta Alagável (classe 6),\n  - 0.810% de Pastagem (classe 15),\n  - 0.374% de Rio (classe 33).\n</ul>\n  \nA composição da **paisagem 3** é: \n</ul>\n  - 68.1% de Formação Florestal (classe 3), \n  - 2.26% de Floresta Alagável (classe 6), \n  - 2.18% Campo Alagado e Área Pantanosa (classe 11), \n  - 0.507% de Formação Campestre (classe 12), \n  - 9.73% de Pastagem (classe 15),\n  - 17.2% de Rio (classe 33).\n</ul>\n  \n![ ](RDS_Landscapes.png)",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}